<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HossainXPS8960" failures="1" tests="5" name="Test" time="0.032" errors="0" timestamp="2024-11-20T22:01:53 EST">
  <testcase classname="tests.Demo" name="sampleOne" time="0.005"/>
  <testcase classname="tests.Demo" name="sampleThree" time="0.001"/>
  <testcase classname="tests.Demo" name="sampleTwo" time="0.001">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <testcase classname="tests.Demo" name="sampleTwo" time="0.001">
    <skipped/>
  </testcase> <!-- sampleTwo -->
  <testcase classname="tests.Demo" name="sampleTwo" time="0.0">
    <failure type="java.lang.AssertionError" message="Intentionally failing the test">
      <![CDATA[java.lang.AssertionError: Intentionally failing the test
at tests.Demo.sampleTwo(Demo.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- sampleTwo -->
</testsuite> <!-- Test -->
